### ISSUE TITLE
Should VFB be using MEAN scores for NBLAST queries by default?

### ISSUE THREAD

**Issue by Robbie1977** [jefferis/vfbr#11]
Should VFB be using MEAN scores for NBLAST queries by default?

@jefferis Which should we be using as currently uses non-mean?

**Comment by jefferis** [comment]
It depends what you are doing. For NBLAST against GMR database, no. For flycircuit to flycircuit, maybe. In general if you want to find the most similar neuron to a query neuron, then mean has the advantage of getting rid of low specificity matches. It is a little more expensive as forward queries can read a contiguous chunk of score matrix from disk, whereas reverse must read every a subset.

**Comment by Robbie1977** [comment]
Can we add it as a passed option then we can change in our end rather than the R but might be good to set a sensible default behaviour?

I believe @mmc46 told me a while ago to use mean for neuron 2 neuron comparisons. 
The results do look tighter on my current random example: http://nblast.virtualflybrain.org:8080/NBLAST_on-the-fly/?all_query=fru-F-400142&all_use_mean=T&gal4_n=10&gal4_query=&tab=One%20against%20all

**Comment by mmc46** [comment]
If you're doing neuron to neuron, then yes, the default can be mean.
Against GMR, like @jefferis said, non-mean is better

**Comment by jefferis** [comment]
It is already an option. You can do e.g. :

```
curl http://r.virtualflybrain.org/ocpu/library/vfbr/R/vfb_nblast/json   -d 'query="FruMARCM-M002262_seg001"&normalisation="mean"&n=5'
```
