### ISSUE TITLE
Change vfbdev.inf.ed.ac.uk to r.virtualflybrain.org

### ISSUE THREAD

**Issue by mmc46** [jefferis/vfbr#8]
https://github.com/jefferis/vfbr/blob/master/R/vfb_nblast.R

needs changing all refs from vfbdev.inf.ed.ac.uk to r.virtualflybrain.org direct

**Comment by jefferis** [comment]
So I've made a change to address this, but am still waiting to hear from @Robbie1977 about some of the other protocols (OWL, solr etc)

**Comment by jefferis** [comment]
See https://github.com/jefferis/vfbr/commit/b3e72479a9d7a06464b5222a8068f441f54de879
